environment: local
verbose: true
aws:
  key: ""
  secret: ""
aiModel:
  provider: "vertex"
  projectID: ""
  location: "us-central1"
  modelID: "gemini-pro-vision"
  apiKey: ""
  parameters:
    temperature: 0.2
    maxOutputTokens: 1024
mockResponse: "This is a mock response for image analysis. The service is configured to use the mock provider."
